In [ ]:
#体验
numpy 操作简单

In [19]:
import numpy as np
a = np.array([
    [3,  4],
    [2, 16]
])

b = np.linalg.inv(a)

print b
print b.shape
print np.dot(a,b)
print np.dot(b,a)

c = np.array([
    [3,  4],
    [2, 16],
    [3, 8]
])

print c.shape

c.shape = 2, 3
print c

d= np.array([[[ 1 , 2] ,[ 3  ,4]  ,[ 5  ,6]] , 
          [[ 7  ,8]  ,[ 9 ,10]  ,[11, 12]]]  )
print "d", d
print d.shape

e = np.arange(0, 60, 10).reshape(-1, 1) + np.arange(0, 6)
print e

[[ 0.4   -0.1  ]
 [-0.05   0.075]]
(2, 2)
[[ 1.  0.]
 [ 0.  1.]]
[[ 1.  0.]
 [ 0.  1.]]
(3, 2)
[[ 3  4  2]
 [16  3  8]]
d [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)
[[ 0]
 [10]
 [20]
 [30]
 [40]
 [50]]


In [11]:
a = np.arange(10)
print a

[0 1 2 3 4 5 6 7 8 9]


In [30]:
# -*- coding: utf-8 -*-

""" @Time : 2017/8/17 18:07 @Author : typhoon @Site : @File : test_has_package_python3.py @Software: PyCharm @desc : parse pdf """

import importlib
import sys
import random


from pdfminer.converter import PDFPageAggregator
from pdfminer.layout import LTTextBoxHorizontal, LAParams
from pdfminer.pdfinterp import PDFResourceManager, PDFPageInterpreter
# from pdfminer.pdfinterp import PDFTextExtractionNotAllowed
from pdfminer.pdfparser import PDFParser, PDFDocument

''' 解析pdf 文本，保存到txt文件中 '''
importlib.reload(sys)



def parse(_path):
    fp = open(_path, 'rb') # rb以二进制读模式打开本地pdf文件


    # 用文件对象来创建一个pdf文档分析器
    praser_pdf = PDFParser(fp)

    # 创建一个PDF文档
    doc = PDFDocument()

    # 连接分析器 与文档对象
    praser_pdf.set_document(doc)
    doc.set_parser(praser_pdf)

    # 提供初始化密码doc.initialize("123456")
    # 如果没有密码 就创建一个空的字符串
    doc.initialize()

    # 检测文档是否提供txt转换，不提供就忽略
    if not doc.is_extractable:
        raise PDFTextExtractionNotAllowed
    else:
        # 创建PDf资源管理器 来管理共享资源
        rsrcmgr = PDFResourceManager()

        # 创建一个PDF参数分析器
        laparams = LAParams()

        # 创建聚合器
        device = PDFPageAggregator(rsrcmgr, laparams=laparams)

        # 创建一个PDF页面解释器对象
        interpreter = PDFPageInterpreter(rsrcmgr, device)

        # 循环遍历列表，每次处理一页的内容
        # doc.get_pages() 获取page列表
        for page in doc.get_pages():
            # 使用页面解释器来读取
            interpreter.process_page(page)

            # 使用聚合器获取内容
            layout = device.get_result()

            # 这里layout是一个LTPage对象 里面存放着 这个page解析出的各种对象 一般包括LTTextBox, LTFigure, LTImage, LTTextBoxHorizontal 等等 想要获取文本就获得对象的text属性，
            for out in layout:
                # 判断是否含有get_text()方法，图片之类的就没有
                # if hasattr(out,"get_text"):
                if isinstance(out, LTTextBoxHorizontal):

                    results = out.get_text()
                    print("results: " + results)
if __name__ == '__main__':
    url = "/home/mm/a.pdf"
    parse(url)

ImportError: cannot import name PDFDocument